using System.Collections;
using System.Collections.Generic;
using System.Drawing;
using UnityEngine;
using Color = UnityEngine.Color;

public class GameManager : MonoBehaviour
{
    // Noise generated by player
    private int noise;
    private GameObject p2Camera;
    private Rect fullScreen;
    private Rect splitScreen;
    private Rect splitBorder;
    public bool isScreenSplit;
    public bool canSplitScreen;

    public int Noise
    {
        get => noise;
        private set
        {
            if (noise - value < 0)
                noise = value;
        }
    }

    private int alarmLevel;

    public int AlarmLevel
    {
        get => alarmLevel;
        private set
        {
            if (alarmLevel - value < 0)
                alarmLevel = value;
        }
    }

    public Player player1;
    public Player player2;


    // Start is called before the first frame update
    private void Start()
    {
        noise = 0;
        player1.SetPlayerControls(1);
        player2.SetPlayerControls(2);
        p2Camera = player2.transform.Find("Camera_P2").gameObject;
        fullScreen = Camera.main.rect;
        splitScreen = new Rect(0, 0, 0.5f, 1);
        float height = Camera.main.orthographicSize * 2.0f;
        float width = height * Screen.width / Screen.height;
        splitBorder = new Rect(Camera.main.transform.position, new Vector2(width, height));
        splitBorder.size *= 0.9f;
        isScreenSplit = false;
        canSplitScreen = true;
    }

    // Update is called once per frame
    private void Update()
    {
        splitBorder.center = Camera.main.transform.position;

        float dist = Vector3.Distance(player1.transform.position, player2.transform.position);
       // print("Distance to other: " + dist);
        
        if (p2Camera != null)
        {
            if (splitBorder.Contains(player2.transform.position))
            {
                p2Camera.SetActive(false);
                Camera.main.rect = fullScreen;
                isScreenSplit = false;
            }
            else
            {
                p2Camera.SetActive(true);
                Camera.main.rect = splitScreen;
                if (canSplitScreen)
                {
                    isScreenSplit = true;
                }
            }
            
        }
    }

    private void OnGUI()
    {
        if(isScreenSplit)
            Drawing.DrawLine(new Vector2(Screen.width/2f, 0), new Vector2(Screen.width / 2f, Screen.height), Color.white, 10f, true);
    }
}