using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    // Noise generated by player
    private int noise;
    public int Noise
    {
        get
        {
            return this.noise;
        }
        private set
        {
            if (this.noise - value < 0)
                this.noise = value;
        }
    }

    private int alarmLevel;
    public int AlarmLevel
    {
        get
        {
            return this.alarmLevel;
        }
        private set
        {
            if (this.alarmLevel - value < 0)
                this.alarmLevel = value;
        }
    }

    public Character player1;
    public Character player2;
    

    // Start is called before the first frame update
    void Start()
    {
        noise = 0;
        player1.SetPlayerControls(1);
        player2.SetPlayerControls(2);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
