using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameManager : MonoBehaviour
{
    // Noise generated by player
    private int noise;

    public int Noise
    {
        get => noise;
        private set
        {
            if (noise - value < 0)
                noise = value;
        }
    }

    private int alarmLevel;
    public int AlarmLevel
    {
        get => alarmLevel;
        private set
        {
            if (alarmLevel - value < 0)
                alarmLevel = value;
        }
    }

    public Player player1;
    public Player player2;


    // Start is called before the first frame update
    private void Start()
    {
        noise = 0;
        player1.SetPlayerControls(1);
        player2.SetPlayerControls(2);
    }

    // Update is called once per frame
    private void Update()
    {
        
    }
}
